// Normalized catalog. Imagery is real — flat-lays from the original mockup,
// boutique editorial from the shop's lookbook. Copy is curatorial, not
// invented claims about provenance unless drawn from the source PDF
// (the Two Tone Pants details come straight from the original product page).

export type Product = {
  slug: string;
  name: string;
  designer?: string;
  price: number;
  fromPrice?: boolean;
  collections: string[]; // collection slugs
  era?: "now" | "then";
  palette: string[]; // hex chips
  images: string[]; // relative public paths
  blurb: string;
  story?: string;
  details?: string[];
  sizes?: string[];
  variant?: { label: string; value: string }[];
  featured?: boolean;
};

export const products: Product[] = [
  {
    slug: "two-tone-pants",
    name: "Two Tone Pants",
    designer: "Seek Collective",
    price: 249,
    collections: ["now", "ready-to-wear"],
    era: "now",
    palette: ["#c8595a", "#d57584"],
    images: [
      "/images/products/two-tone-pants.webp",
      "/images/products/two-tone-pants-2.webp",
    ],
    blurb: "Raspberry colorblocking · straight-leg.",
    story:
      "Seek Collective is a line of elevated essentials inspired by the global woman. They blend art, craft and design to create items that are luxurious, sensible and timeless — designed in Brooklyn, ethically manufactured by artisan communities in India.",
    details: [
      "Flat front, elastic at the back",
      "Hits above the ankles",
      "Button closure at wearer’s left",
      "Side slit pockets at front, welt pockets at back",
      "Naturally dyed",
      "100% organic cotton twill (not pre-shrunk)",
      "Made in India",
    ],
    sizes: ["XS", "S", "M", "L"],
    featured: true,
  },
  {
    slug: "tiger-brooch",
    name: "Tiger Talisman Brooch",
    designer: "Atelier Two",
    price: 185,
    collections: ["objects", "now"],
    era: "now",
    palette: ["#c0392b", "#f1c40f", "#27ae60"],
    images: ["/images/products/tiger-brooch.webp"],
    blurb: "Hand-beaded — one of one.",
    story: "Beaded in-house over the course of a slow week, set on velvet backing.",
    details: ["Glass beads on linen", "Sterling pin", "Roughly 5 × 4 in"],
    featured: true,
  },
  {
    slug: "audette-circle-bag",
    name: "Audette's Circle Bag",
    designer: "Audette",
    price: 310,
    fromPrice: true,
    collections: ["now"],
    era: "now",
    palette: ["#3a5a40", "#b08433"],
    images: ["/images/products/audette-circle-bag.webp"],
    blurb: "Forest leather · brass clasp.",
    sizes: ["One Size"],
    featured: true,
  },
  {
    slug: "floral-jumpsuit",
    name: "Garden Wrap Jumpsuit",
    price: 268,
    collections: ["now", "ready-to-wear"],
    era: "now",
    palette: ["#1f3b2a", "#d4a373"],
    images: ["/images/products/floral-jumpsuit.webp"],
    blurb: "Botanical print, easy through the shoulder.",
    sizes: ["XS", "S", "M", "L"],
    featured: true,
  },
  {
    slug: "denim-jumpsuit",
    name: "Indigo Workroom Jumpsuit",
    price: 224,
    collections: ["now", "ready-to-wear"],
    era: "now",
    palette: ["#2c3e6b"],
    images: ["/images/products/denim-jumpsuit.webp"],
    blurb: "Soft indigo with a relaxed leg.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "soul-queen-tee",
    name: "Soul Queen Tee",
    price: 64,
    collections: ["now"],
    era: "now",
    palette: ["#f4efe6", "#1c1814"],
    images: ["/images/products/soul-queen-tee.webp"],
    blurb: "Hand-printed cotton.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    slug: "jaguar-necklace",
    name: "Jaguar Pectoral Necklace",
    designer: "Atelier Two",
    price: 425,
    collections: ["objects", "jewelry"],
    era: "now",
    palette: ["#0f5132", "#bf2026", "#1a5a8a"],
    images: ["/images/products/jaguar-necklace.webp"],
    blurb: "Beaded statement piece on cotton cord.",
    featured: true,
  },
  {
    slug: "fox-clutch",
    name: "Fox Spirit Clutch",
    designer: "Atelier Two",
    price: 380,
    collections: ["objects"],
    era: "now",
    palette: ["#5b8c5a", "#a3c4bc"],
    images: ["/images/products/fox-clutch.webp"],
    blurb: "Hand-beaded clutch — sage and lilac.",
  },
  {
    slug: "lightning-necklace",
    name: "Lightning Mouth Necklace",
    designer: "Atelier Two",
    price: 295,
    collections: ["objects", "jewelry"],
    era: "now",
    palette: ["#bf2026", "#7a1a1e"],
    images: ["/images/products/lightning-necklace.webp"],
    blurb: "Beaded, mounted on cord.",
  },
  {
    slug: "bib-necklace",
    name: "Heirloom Bib Necklace",
    price: 156,
    collections: ["jewelry"],
    era: "now",
    palette: ["#e8c5a0", "#d4a373"],
    images: ["/images/products/bib-necklace.webp"],
    blurb: "Layered glass and pearl.",
  },
  {
    slug: "crystal-necklace",
    name: "Crystal Curtain Necklace",
    price: 142,
    collections: ["jewelry"],
    era: "now",
    palette: ["#cfd6dd"],
    images: [
      "/images/products/crystal-necklace.webp",
      "/images/products/crystal-necklace-2.webp",
    ],
    blurb: "Multi-strand statement.",
  },
  {
    slug: "chandelier-earrings",
    name: "Chandelier Earrings",
    price: 88,
    collections: ["jewelry"],
    era: "now",
    palette: ["#e63946", "#7a1a1e"],
    images: [
      "/images/products/chandelier-earrings.webp",
      "/images/products/chandelier-earrings-2.webp",
    ],
    blurb: "Crimson stones, antique brass.",
  },
  {
    slug: "gold-dome-earrings",
    name: "Gold Dome Earrings",
    price: 74,
    collections: ["jewelry"],
    era: "now",
    palette: ["#b08433", "#caa052"],
    images: ["/images/products/gold-dome-earrings.webp"],
    blurb: "Cast brass, weighty.",
  },
  {
    slug: "studded-cuff",
    name: "Studded Cuff",
    price: 168,
    collections: ["jewelry", "then"],
    era: "then",
    palette: ["#1c1814", "#b08433"],
    images: ["/images/products/studded-cuff.webp"],
    blurb: "1980s leather cuff with brass tacks.",
  },
  {
    slug: "rose-sequin-top",
    name: "Rose Sequin Blouse",
    price: 198,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#c98a7d"],
    images: ["/images/products/rose-sequin-top.webp"],
    blurb: "All-over sequin, puff sleeve.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "sequin-blazer",
    name: "Midnight Sequin Blazer",
    price: 245,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#0a0a0a"],
    images: [
      "/images/products/sequin-blazer.webp",
      "/images/products/sequin-blazer-2.webp",
    ],
    blurb: "Black-on-black sparkle.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "cobalt-romper",
    name: "Cobalt One-Shoulder Romper",
    price: 178,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#1f4ec4"],
    images: ["/images/products/cobalt-romper.webp"],
    blurb: "Cobalt crêpe with a sculpted bow.",
    sizes: ["XS", "S", "M"],
  },
  {
    slug: "gold-trousers",
    name: "Gilded Wide-Leg Trousers",
    price: 192,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#a98038"],
    images: ["/images/products/gold-trousers.webp"],
    blurb: "Liquid metallic, elasticated waist.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "burgundy-coat",
    name: "Burgundy Fur-Collar Coat",
    price: 425,
    collections: ["then"],
    era: "then",
    palette: ["#5b1a1a"],
    images: ["/images/products/burgundy-coat.webp"],
    blurb: "1970s wool with detachable fur collar.",
    sizes: ["S", "M"],
  },
  {
    slug: "black-skirt",
    name: "Tea-Length Tulip Skirt",
    price: 134,
    collections: ["ready-to-wear"],
    era: "now",
    palette: ["#0a0a0a"],
    images: ["/images/products/black-skirt.webp"],
    blurb: "Faille with a soft pleat.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "cape-set",
    name: "Cape Trouser Set",
    price: 268,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#0a0a0a"],
    images: ["/images/products/cape-set.webp"],
    blurb: "Two-piece — cape blouse & trouser.",
    sizes: ["XS", "S", "M"],
  },
  {
    slug: "polkadot-maxi",
    name: "Constellation Maxi Skirt",
    price: 184,
    collections: ["ready-to-wear"],
    era: "now",
    palette: ["#0a0a0a", "#f4efe6"],
    images: ["/images/products/polkadot-maxi.webp"],
    blurb: "Black silk dotted with white stars.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "shirtdress",
    name: "Schoolhouse Shirtdress",
    price: 168,
    collections: ["ready-to-wear"],
    era: "now",
    palette: ["#0a0a0a"],
    images: ["/images/products/shirtdress.webp"],
    blurb: "Crisp collar, dotted ground.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "blush-gown",
    name: "Blush Halter Gown",
    price: 326,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#e8c0bf"],
    images: ["/images/products/blush-gown.webp"],
    blurb: "Floor-length with a deep V.",
    sizes: ["XS", "S", "M"],
  },
  {
    slug: "leopard-trousers",
    name: "Leopard Cigarette Trousers",
    price: 188,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#a37b3a", "#1c1814"],
    images: ["/images/products/leopard-trousers.webp"],
    blurb: "High-rise with a slim ankle.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "vintage-green-dress",
    name: "Forest Vintage Slip",
    price: 145,
    collections: ["then", "ready-to-wear"],
    era: "then",
    palette: ["#1f3b2a"],
    images: ["/images/products/vintage-green-dress.webp"],
    blurb: "1990s rayon — one of one.",
    sizes: ["M"],
  },
  {
    slug: "vintage-teal-robe",
    name: "Teal Silk Robe",
    price: 215,
    collections: ["then"],
    era: "then",
    palette: ["#3a8c8c"],
    images: ["/images/products/vintage-teal-robe.webp"],
    blurb: "Hand-embroidered, late 60s.",
    sizes: ["One Size"],
  },
  {
    slug: "peach-top",
    name: "Apricot Knit Cami",
    price: 96,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#e8a884"],
    images: ["/images/products/peach-top.webp"],
    blurb: "Featherweight linen blend.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "gingham-blouse",
    name: "Gingham Field Shirt",
    price: 124,
    collections: ["ready-to-wear", "now"],
    era: "now",
    palette: ["#2c3e6b", "#f4efe6"],
    images: ["/images/products/gingham-blouse.webp"],
    blurb: "Classic checks, oversized fit.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    slug: "coral-clutch",
    name: "Coral Plush Clutch",
    price: 142,
    collections: ["now"],
    era: "now",
    palette: ["#e89684"],
    images: ["/images/products/coral-clutch.webp"],
    blurb: "Tufted velvet, brass kiss-clasp.",
  },
  {
    slug: "red-tote",
    name: "Pillar Box Tote",
    price: 198,
    collections: ["now"],
    era: "now",
    palette: ["#c0392b"],
    images: ["/images/products/red-tote.webp"],
    blurb: "Soft Italian leather.",
  },
  {
    slug: "eyelash-clutch",
    name: "Eyelash Cat Clutch",
    designer: "Kate Spade",
    price: 268,
    collections: ["then"],
    era: "then",
    palette: ["#0a0a0a", "#e8c0bf"],
    images: ["/images/products/eyelash-clutch.webp"],
    blurb: "Whimsy with a chain strap.",
  },
  {
    slug: "tortoise-sunglasses",
    name: "Tortoise Disc Sunglasses",
    price: 92,
    collections: ["now"],
    era: "now",
    palette: ["#8a5a2a"],
    images: ["/images/products/tortoise-sunglasses.webp"],
    blurb: "Acetate, round.",
  },
  {
    slug: "cateye-sunglasses",
    name: "Smoke Cat-Eye Sunglasses",
    price: 84,
    collections: ["now"],
    era: "now",
    palette: ["#0a0a0a", "#6b6157"],
    images: ["/images/products/cateye-sunglasses.webp"],
    blurb: "Graduated lens.",
  },
  {
    slug: "hair-comb",
    name: "Crystal Hair Comb",
    price: 78,
    collections: ["jewelry"],
    era: "now",
    palette: ["#cfd6dd"],
    images: [
      "/images/products/hair-comb.webp",
      "/images/products/hair-comb-2.webp",
    ],
    blurb: "Hand-set crystal.",
  },
  {
    slug: "patent-pumps",
    name: "Patent Pump",
    designer: "Steve Madden",
    price: 132,
    collections: ["now"],
    era: "now",
    palette: ["#0a0a0a"],
    images: [
      "/images/products/patent-pumps.webp",
      "/images/products/patent-pumps-2.webp",
      "/images/products/patent-pumps-3.webp",
      "/images/products/patent-pumps-4.webp",
    ],
    blurb: "Pointed-toe d'Orsay.",
    sizes: ["6", "7", "8", "9", "10"],
  },
  // Fragrance series — kept as a small set in a single product card.
  {
    slug: "ds-durga-fragrance",
    name: "D.S. & Durga · Eau de Parfum",
    designer: "D.S. & Durga",
    price: 195,
    collections: ["fragrance"],
    era: "now",
    palette: ["#a3b899", "#1c1814"],
    images: ["/images/products/fragrance-set.webp"],
    blurb: "Four scents — choose your weather.",
    variant: [
      { label: "Scent", value: "White Peacock Lily" },
      { label: "Scent", value: "Radio Bombay" },
      { label: "Scent", value: "Debaser" },
      { label: "Scent", value: "Reetrapper" },
    ],
    featured: true,
  },
];

export const findProduct = (slug: string) =>
  products.find((p) => p.slug === slug);

export const productsByCollection = (col: string) =>
  products.filter((p) => p.collections.includes(col));

export const featured = () => products.filter((p) => p.featured);

// Curated home grid ordering — deliberately mixes ghost-on-cream flat-lays
// with full-bleed editorial color so the page breathes the way the mockup does.
export const homeGridOrder: string[] = [
  "tiger-brooch",
  "red-tote",
  "floral-jumpsuit",
  "gold-trousers",
  "rose-sequin-top",
  "ds-durga-fragrance",
  "vintage-green-dress",
  "gingham-blouse",
  "jaguar-necklace",
  "soul-queen-tee",
  "denim-jumpsuit",
  "bib-necklace",
  "vintage-teal-robe",
  "gold-dome-earrings",
  "tortoise-sunglasses",
  "sequin-blazer",
  "studded-cuff",
  "crystal-necklace",
  "cateye-sunglasses",
  "polkadot-maxi",
  "shirtdress",
  "hair-comb",
  "blush-gown",
  "chandelier-earrings",
  "audette-circle-bag",
  "fox-clutch",
  "lightning-necklace",
  "leopard-trousers",
  "two-tone-pants",
  "cobalt-romper",
  "burgundy-coat",
  "coral-clutch",
  "patent-pumps",
  "eyelash-clutch",
  "peach-top",
  "cape-set",
];
